// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7yGIiu3s0NzygSGapxLi2Bu2At6fGsGk',
    appId: '1:1006740265489:web:d9f19c9f6349446c30efb0',
    messagingSenderId: '1006740265489',
    projectId: 'mapsproject-af9c1',
    authDomain: 'mapsproject-af9c1.firebaseapp.com',
    storageBucket: 'mapsproject-af9c1.firebasestorage.app',
    measurementId: 'G-C7ST6B3505',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBz5PR9gayHvqIn-pHgtha3DV_Kj320jo',
    appId: '1:1006740265489:android:d329527aa03c6a9130efb0',
    messagingSenderId: '1006740265489',
    projectId: 'mapsproject-af9c1',
    storageBucket: 'mapsproject-af9c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-u2jGerr19tb-f6AfYYYWVoiNaFQkwu0',
    appId: '1:1006740265489:ios:8df4b3463391fe3a30efb0',
    messagingSenderId: '1006740265489',
    projectId: 'mapsproject-af9c1',
    storageBucket: 'mapsproject-af9c1.firebasestorage.app',
    iosBundleId: 'com.example.mapsLocation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-u2jGerr19tb-f6AfYYYWVoiNaFQkwu0',
    appId: '1:1006740265489:ios:8df4b3463391fe3a30efb0',
    messagingSenderId: '1006740265489',
    projectId: 'mapsproject-af9c1',
    storageBucket: 'mapsproject-af9c1.firebasestorage.app',
    iosBundleId: 'com.example.mapsLocation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7yGIiu3s0NzygSGapxLi2Bu2At6fGsGk',
    appId: '1:1006740265489:web:a9e12d7649e7b2c630efb0',
    messagingSenderId: '1006740265489',
    projectId: 'mapsproject-af9c1',
    authDomain: 'mapsproject-af9c1.firebaseapp.com',
    storageBucket: 'mapsproject-af9c1.firebasestorage.app',
    measurementId: 'G-M7HK3GPE8D',
  );
}
